Repository VulnerabilityHistoryProject/ffmpeg-vulnerabilities, pull requests merged in 2022-05, with the labels that each got.

#17 CVE-2013-2276 and CVE-2013-4263
  cves/CVE-2013-2276.yml
  cves/CVE-2013-4263.yml
Labels: cohort d, great work!

#18 CVE-2015-8364 and CVE-2013-0854
  cves/CVE-2013-0854.yml
  cves/CVE-2015-8364.yml
Labels: cohort a, great work!

#19 CVE-2018-12460 and CVE-2016-7122
  cves/CVE-2016-7122.yml
  cves/CVE-2018-12460.yml
Labels: cohort c

#22 CVE-2019-11339&CVE-2017-11665
  cves/CVE-2017-11665.yml
  cves/CVE-2019-11339.yml
Labels: cohort m

#24 CVE-2016-2327 and CVE-2019-11338
  cves/CVE-2016-2327.yml
  cves/CVE-2019-11338.yml
Labels: cohort l

#26 CVE-2012-2774 and CVE-2012-2775
  cves/CVE-2012-2774.yml
  cves/CVE-2012-2775.yml
Labels: cohort o

#28 CVE-2015-8218 and CVE-2017-14170
  cves/CVE-2015-8218.yml
  cves/CVE-2017-14170.yml
Labels: cohort g

#31 CVE-2013-0867 and CVE-2013-2277
  cves/CVE-2013-0867.yml
  cves/CVE-2013-2277.yml
Labels: cohort b

#32 Document vulnerability CVE-2017-9608 and CVE-2013-0844
  cves/CVE-2013-0844.yml
  cves/CVE-2017-9608.yml
Labels: cohort b

#33 CVE-2011-0722 and CVE-2015-6826
  cves/CVE-2011-0722.yml
  cves/CVE-2015-6826.yml
Labels: cohort g

#34 CVE-2015-1872 and CVE-2017-11719
  cves/CVE-2015-1872.yml
  cves/CVE-2017-11719.yml
Labels: cohort f, great work!

#36 CVE-2013-0861 and CVE-2016-10192
  cves/CVE-2013-0861.yml
  cves/CVE-2016-10192.yml
Labels: cohort d

#37 CVE-2015-6821 and CVE-2017-14059
  cves/CVE-2015-6821.yml
  cves/CVE-2017-14059.yml
Labels: cohort f

#3 CVE-2010-4704 and CVE-2011-3951
  cves/CVE-2010-4704.yml
  cves/CVE-2011-3951.yml
Labels: cohort h, great work!

#21 CVE-2011-3944 and CVE-2012-6617
  cves/CVE-2011-3944.yml
  cves/CVE-2012-6617.yml
Labels: cohort a

#16 CVE-2013-0847 and CVE-2014-8547
  cves/CVE-2013-0847.yml
  cves/CVE-2014-8547.yml
Labels: cohort e

#15 CVE-2018-13302 and CVE-2013-0856
  cves/CVE-2013-0856.yml
  cves/CVE-2018-13302.yml
Labels: cohort m

#14 CVE-2013-0865 and CVE-2013-7024
  cves/CVE-2013-0865.yml
  cves/CVE-2013-7024.yml
Labels: cohort i

#12 CVE-2018-9841 and CVE-2018-1999015
  cves/CVE-2018-1999015.yml
  cves/CVE-2018-9841.yml
Labels: cohort c

#11 CVE-2013-7014 and CVE-2018-14394
  .vscode/settings.json
  cves/CVE-2013-7014.yml
  cves/CVE-2018-14394.yml
Labels: cohort d

#10 CVE-2012-0848 and CVE-2018-6621
  cves/CVE-2012-0848.yml
  cves/CVE-2018-6621.yml
Labels: cohort j

#9 CVE-2013-3674 and CVE-2017-7866
  cves/CVE-2013-3674.yml
  cves/CVE-2017-7866.yml
Labels: cohort o

#8 CVE-2017-16840 and CVE-2012-2779
  cves/CVE-2012-2779.yml
  cves/CVE-2017-16840.yml
Labels: cohort n

#7 cve-2012-0858 and cve-2017-14058
  cves/CVE-2012-0858.yml
  cves/CVE-2017-14058.yml
Labels: cohort i

#6 CVE-2017-14056 and CVE-2018-13304
  cves/CVE-2017-14056.yml
  cves/CVE-2018-13304.yml
Labels: cohort k

#2 CVE-2018-6912 and CVE-2013-0868
  cves/CVE-2013-0868.yml
  cves/CVE-2018-6912.yml
Labels: cohort k, great work!
